import { PrismaClient, HospitalStatus, TraumaLevel } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🏥 Adding missing hospitals from seed-hospitals-new.ts...');

  const additionalHospitals = [
    {
      id: '10',
      name: 'Al-Rayth General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 567 8901',
      contactEmail: 'alrayth@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '11',
      name: 'Al-Tuwal General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 678 9012',
      contactEmail: 'altuwal@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '12',
      name: 'Al-Aridha General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 789 0123',
      contactEmail: 'alaridha@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '13',
      name: 'Al-Muwassam General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
  
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 890 1234',
      contactEmail: 'almuwassam@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '14',
      name: 'Ahad Al-Masarhah General Hospital',
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 901 2345',
      contactEmail: 'ahad@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '15',
      name: 'Bani Malik General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 012 3456',
      contactEmail: 'banimalik@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '16',
      name: 'Eradah Mental Health Complex',
      icuBeds: 10,
      icuBedsAvailable: 5,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 20,
      maleBedsAvailable: 10,
      femaleBeds: 20,
      femaleBedsAvailable: 10,
      pediatricBeds: 10,
      pediatricBedsAvailable: 5,
      standardBeds: 50,
      standardBedsAvailable: 25,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 123 4567',
      contactEmail: 'eradah@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 5,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '17',
      name: 'Chest Diseases Hospital',
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 234 5678',
      contactEmail: 'chest@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '18',
      name: 'Al-Aidabi General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 345 6789',
      contactEmail: 'alaidabi@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '19',
      name: 'Dhamad General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 456 7890',
      contactEmail: 'dhamad@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '20',
      name: 'Farasan General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 567 8901',
      contactEmail: 'farasan@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '21',
      name: 'Fayfa General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 678 9012',
      contactEmail: 'fayfa@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '23',
      name: 'PHC Centers',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 55 890 1234',
      contactEmail: 'phc@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '24',
      name: 'Private Hospital',
      address: 'Various Private Locations',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 901 2345',
      contactEmail: 'private@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '25',
      name: 'Other Hospital',
      address: 'External Healthcare Facility',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 012 3456',
      contactEmail: 'other@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
  ];

  let addedCount = 0;
  let skippedCount = 0;

  for (const hospital of additionalHospitals) {
    try {
      await prisma.hospital.upsert({
        where: { id: hospital.id },
        update: hospital,
        create: hospital,
      });
      console.log(`✅ Added hospital: ${hospital.name}`);
      addedCount++;
    } catch (error) {
      console.log(`⚠️  Hospital ${hospital.name} already exists, skipping...`);
      skippedCount++;
    }
  }

  console.log(`✅ Added ${addedCount} new hospitals, skipped ${skippedCount} existing ones`);
  console.log('🏥 All hospitals from seed-hospitals-new.ts have been added!');
}

main()
  .catch((e) => {
    console.error('❌ Error adding hospitals:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
