import { PrismaClient, HospitalStatus, TraumaLevel } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting hospital data seeding...');
  // Seed hospitals based on CSV data
  const hospitals = [
    {
      id: '4',
      name: 'Samtah General Hospital',
      address: 'Samtah, Jazan, Saudi Arabia',
      latitude: 16.6050,
      longitude: 42.9419,
      icuBeds: 10,
      icuBedsAvailable: 4,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 25,
      maleBedsAvailable: 10,
      femaleBeds: 25,
      femaleBedsAvailable: 10,
      pediatricBeds: 10,
      pediatricBedsAvailable: 4,
      standardBeds: 60,
      standardBedsAvailable: 24,
      ventilators: 8,
      ventilatorsAvailable: 4,
      hasStemiService: false,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 58 211 9876',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '6',
      name: 'Abu Arish General Hospital (AAGH)',
      address: 'Abu Arish, Jazan, Saudi Arabia',
      latitude: 16.9815,
      longitude: 42.8326,
      icuBeds: 12,
      icuBedsAvailable: 5,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 30,
      maleBedsAvailable: 15,
      femaleBeds: 30,
      femaleBedsAvailable: 12,
      pediatricBeds: 12,
      pediatricBedsAvailable: 5,
      standardBeds: 72,
      standardBedsAvailable: 32,
      ventilators: 10,
      ventilatorsAvailable: 6,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 55 987 6321',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '7',
      name: 'Sabya General Hospital',
      icuBeds: 10,
      icuBedsAvailable: 5,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 20,
      maleBedsAvailable: 10,
      femaleBeds: 20,
      femaleBedsAvailable: 10,
      pediatricBeds: 10,
      pediatricBedsAvailable: 5,
      standardBeds: 50,
      standardBedsAvailable: 25,
      ventilators: 5,
      ventilatorsAvailable: 2,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 5,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '8',
      name: 'Baysh General Hospital',
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      ventilators: 4,
      ventilatorsAvailable: 2,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '9',
      name: 'Al-Hurrath General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '10',
      name: 'Al-Darb General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '11',
      name: 'Al-Rayth General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '12',
      name: 'Al-Tuwal General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '13',
      name: 'Al-Aridha General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '14',
      name: 'Al-Muwassam General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '15',
      name: 'Ahad Al-Masarhah General Hospital',
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      ventilators: 4,
      ventilatorsAvailable: 2,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '16',
      name: 'Bani Malik General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '17',
      name: 'Eradah Mental Health Complex',
      icuBeds: 10,
      icuBedsAvailable: 5,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 20,
      maleBedsAvailable: 10,
      femaleBeds: 20,
      femaleBedsAvailable: 10,
      pediatricBeds: 10,
      pediatricBedsAvailable: 5,
      standardBeds: 50,
      standardBedsAvailable: 25,
      ventilators: 5,
      ventilatorsAvailable: 2,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 5,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '18',
      name: 'Chest Diseases Hospital',
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      ventilators: 4,
      ventilatorsAvailable: 2,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '19',
      name: 'Al-Aidabi General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '20',
      name: 'Dhamad General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '21',
      name: 'Farasan General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '22',
      name: 'Fayfa General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '23',
      name: 'Jazan Specialized Hospital',
      icuBeds: 15,
      icuBedsAvailable: 8,
      picuBeds: 8,
      picuBedsAvailable: 4,
      maleBeds: 30,
      maleBedsAvailable: 15,
      femaleBeds: 30,
      femaleBedsAvailable: 15,
      pediatricBeds: 15,
      pediatricBedsAvailable: 8,
      standardBeds: 60,
      standardBedsAvailable: 30,
      ventilators: 10,
      ventilatorsAvailable: 5,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 8,
      nicuBedsAvailable: 4,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '24',
      name: 'PHC Centers',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      ventilators: 0,
      ventilatorsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '25',
      name: 'Private Hospital',
      address: 'Various Private Locations',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      ventilators: 0,
      ventilatorsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '26',
      name: 'Other Hospital',
      address: 'External Healthcare Facility',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      ventilators: 0,
      ventilatorsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '1',
      name: 'Jazan General Hospital (JGH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.8892,
      longitude: 42.5611,
      icuBeds: 20,
      icuBedsAvailable: 10,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 40,
      maleBedsAvailable: 15,
      femaleBeds: 35,
      femaleBedsAvailable: 12,
      pediatricBeds: 15,
      pediatricBedsAvailable: 5,
      standardBeds: 90,
      standardBedsAvailable: 32,
      ventilators: 15,
      ventilatorsAvailable: 8,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 54 930 0261',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '2',
      name: 'King Fahad Central Hospital (KFCH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.9087,
      longitude: 42.5549,
      icuBeds: 30,
      icuBedsAvailable: 12,
      picuBeds: 8,
      picuBedsAvailable: 3,
      maleBeds: 60,
      maleBedsAvailable: 20,
      femaleBeds: 55,
      femaleBedsAvailable: 18,
      pediatricBeds: 25,
      pediatricBedsAvailable: 8,
      standardBeds: 140,
      standardBedsAvailable: 46,
      ventilators: 25,
      ventilatorsAvailable: 15,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 503 6789',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: '3',
      name: 'Prince Mohammed Bin Nasser Hospital (PMNH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.8999,
      longitude: 42.5625,
      icuBeds: 15,
      icuBedsAvailable: 7,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 35,
      maleBedsAvailable: 12,
      femaleBeds: 30,
      femaleBedsAvailable: 10,
      pediatricBeds: 15,
      pediatricBedsAvailable: 5,
      standardBeds: 80,
      standardBedsAvailable: 27,
      ventilators: 12,
      ventilatorsAvailable: 6,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 56 128 4567',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
  ];

  for (const hospital of hospitals) {
    await prisma.hospital.create({
      data: hospital,
    });
  }

  console.log(`✅ Successfully seeded ${hospitals.length} hospitals`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding hospitals:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
