import { PrismaClient, HospitalStatus, TraumaLevel } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';

const prisma = new PrismaClient();

// Generate consistent UUIDs for hospitals
const HOSPITAL_IDS = {
  JGH: '550e8400-e29b-41d4-a716-446655440001',
  KFCH: '550e8400-e29b-41d4-a716-446655440002',
  PMNH: '550e8400-e29b-41d4-a716-446655440003',
  SAMTAH: '550e8400-e29b-41d4-a716-446655440004',
  ABU_ARISH: '550e8400-e29b-41d4-a716-446655440005',
  SABYA: '550e8400-e29b-41d4-a716-446655440006',
  BAYSH: '550e8400-e29b-41d4-a716-446655440007',
  AL_HURRATH: '550e8400-e29b-41d4-a716-446655440008',
  AL_DAYER: '550e8400-e29b-41d4-a716-446655440009',
  JAZAN_SPECIALIZED: '550e8400-e29b-41d4-a716-446655440010',
  AL_ARDHAH: '550e8400-e29b-41d4-a716-446655440011',
  AL_REITH: '550e8400-e29b-41d4-a716-446655440012',
  AL_IDABI: '550e8400-e29b-41d4-a716-446655440013',
  AL_AYDABI: '550e8400-e29b-41d4-a716-446655440014',
  AL_RAITH: '550e8400-e29b-41d4-a716-446655440015',
  AL_DAIR: '550e8400-e29b-41d4-a716-446655440016',
  AL_HURRAH: '550e8400-e29b-41d4-a716-446655440017',
  AL_ARDHA: '550e8400-e29b-41d4-a716-446655440018',
  AL_DAYR: '550e8400-e29b-41d4-a716-446655440019',
  AL_HURRA: '550e8400-e29b-41d4-a716-446655440020',
  AL_ARDH: '550e8400-e29b-41d4-a716-446655440021',
  AL_REITH_SPECIALIZED: '550e8400-e29b-41d4-a716-446655440023',
  AL_DAYER_SPECIALIZED: '550e8400-e29b-41d4-a716-446655440024',
  JAZAN_CITY: '550e8400-e29b-41d4-a716-446655440025',
  AL_ARDHAH_SPECIALIZED: '550e8400-e29b-41d4-a716-446655440026',
};

async function seedHospitalsWithUUIDs() {
  console.log('🏥 Seeding hospitals with UUIDs...');
  
  const hospitals = [
    // Major Hospitals with full services
    {
      id: HOSPITAL_IDS.JGH,
      name: 'Jazan General Hospital (JGH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.8892,
      longitude: 42.5611,
      icuBeds: 20,
      icuBedsAvailable: 10,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 40,
      maleBedsAvailable: 15,
      femaleBeds: 35,
      femaleBedsAvailable: 12,
      pediatricBeds: 15,
      pediatricBedsAvailable: 5,
      standardBeds: 90,
      standardBedsAvailable: 32,
      ventilators: 15,
      ventilatorsAvailable: 8,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 54 930 0261',
      contactEmail: 'jgh@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.KFCH,
      name: 'King Fahad Central Hospital (KFCH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.9087,
      longitude: 42.5549,
      icuBeds: 30,
      icuBedsAvailable: 12,
      picuBeds: 8,
      picuBedsAvailable: 3,
      maleBeds: 60,
      maleBedsAvailable: 20,
      femaleBeds: 55,
      femaleBedsAvailable: 18,
      pediatricBeds: 25,
      pediatricBedsAvailable: 8,
      standardBeds: 140,
      standardBedsAvailable: 46,
      ventilators: 25,
      ventilatorsAvailable: 15,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 503 6789',
      contactEmail: 'kfch@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.PMNH,
      name: 'Prince Mohammed Bin Nasser Hospital (PMNH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.8999,
      longitude: 42.5625,
      icuBeds: 15,
      icuBedsAvailable: 7,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 35,
      maleBedsAvailable: 12,
      femaleBeds: 30,
      femaleBedsAvailable: 10,
      pediatricBeds: 20,
      pediatricBedsAvailable: 6,
      standardBeds: 80,
      standardBedsAvailable: 28,
      ventilators: 12,
      ventilatorsAvailable: 6,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 123 4567',
      contactEmail: 'pmnh@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.SAMTAH,
      name: 'Samtah General Hospital',
      address: 'Samtah, Jazan, Saudi Arabia',
      latitude: 16.6000,
      longitude: 42.9500,
      icuBeds: 10,
      icuBedsAvailable: 4,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 25,
      maleBedsAvailable: 8,
      femaleBeds: 20,
      femaleBedsAvailable: 6,
      pediatricBeds: 12,
      pediatricBedsAvailable: 3,
      standardBeds: 60,
      standardBedsAvailable: 18,
      ventilators: 8,
      ventilatorsAvailable: 4,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Samtah',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 234 5678',
      contactEmail: 'samtah@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.ABU_ARISH,
      name: 'Abu Arish General Hospital',
      address: 'Abu Arish, Jazan, Saudi Arabia',
      latitude: 16.9689,
      longitude: 42.8325,
      icuBeds: 12,
      icuBedsAvailable: 5,
      picuBeds: 4,
      picuBedsAvailable: 1,
      maleBeds: 30,
      maleBedsAvailable: 10,
      femaleBeds: 25,
      femaleBedsAvailable: 8,
      pediatricBeds: 15,
      pediatricBedsAvailable: 4,
      standardBeds: 70,
      standardBedsAvailable: 22,
      ventilators: 10,
      ventilatorsAvailable: 5,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Abu Arish',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 345 6789',
      contactEmail: 'abuarish@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.SABYA,
      name: 'Sabya General Hospital',
      address: 'Sabya, Jazan, Saudi Arabia',
      latitude: 17.1497,
      longitude: 42.6253,
      icuBeds: 8,
      icuBedsAvailable: 3,
      picuBeds: 2,
      picuBedsAvailable: 1,
      maleBeds: 20,
      maleBedsAvailable: 6,
      femaleBeds: 18,
      femaleBedsAvailable: 5,
      pediatricBeds: 10,
      pediatricBedsAvailable: 2,
      standardBeds: 50,
      standardBedsAvailable: 15,
      ventilators: 6,
      ventilatorsAvailable: 3,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Sabya',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 456 7890',
      contactEmail: 'sabya@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.BAYSH,
      name: 'Baysh General Hospital',
      address: 'Baysh, Jazan, Saudi Arabia',
      latitude: 17.3333,
      longitude: 42.7333,
      icuBeds: 6,
      icuBedsAvailable: 2,
      picuBeds: 2,
      picuBedsAvailable: 1,
      maleBeds: 15,
      maleBedsAvailable: 4,
      femaleBeds: 12,
      femaleBedsAvailable: 3,
      pediatricBeds: 8,
      pediatricBedsAvailable: 2,
      standardBeds: 35,
      standardBedsAvailable: 10,
      ventilators: 4,
      ventilatorsAvailable: 2,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Baysh',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 567 8901',
      contactEmail: 'baysh@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.AL_HURRATH,
      name: 'Al-Hurrath General Hospital',
      address: 'Al-Hurrath, Jazan, Saudi Arabia',
      latitude: 16.5000,
      longitude: 42.8000,
      icuBeds: 5,
      icuBedsAvailable: 1,
      picuBeds: 1,
      picuBedsAvailable: 0,
      maleBeds: 12,
      maleBedsAvailable: 2,
      femaleBeds: 10,
      femaleBedsAvailable: 2,
      pediatricBeds: 6,
      pediatricBedsAvailable: 1,
      standardBeds: 28,
      standardBedsAvailable: 5,
      ventilators: 3,
      ventilatorsAvailable: 1,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Al-Hurrath',
      status: HospitalStatus.LIMITED,
      contactPhone: '+966 50 678 9012',
      contactEmail: 'alhurrath@moh.gov.sa',
      emergencyDeptStatus: 'limited',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.AL_DAYER,
      name: 'Al-Dayer General Hospital',
      address: 'Al-Dayer, Jazan, Saudi Arabia',
      latitude: 16.7000,
      longitude: 42.9000,
      icuBeds: 7,
      icuBedsAvailable: 2,
      picuBeds: 2,
      picuBedsAvailable: 1,
      maleBeds: 18,
      maleBedsAvailable: 5,
      femaleBeds: 15,
      femaleBedsAvailable: 4,
      pediatricBeds: 9,
      pediatricBedsAvailable: 2,
      standardBeds: 42,
      standardBedsAvailable: 12,
      ventilators: 5,
      ventilatorsAvailable: 2,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Al-Dayer',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 789 0123',
      contactEmail: 'aldayer@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: HOSPITAL_IDS.JAZAN_SPECIALIZED,
      name: 'Jazan Specialized Hospital',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.8892,
      longitude: 42.5611,
      icuBeds: 25,
      icuBedsAvailable: 15,
      picuBeds: 10,
      picuBedsAvailable: 5,
      maleBeds: 50,
      maleBedsAvailable: 25,
      femaleBeds: 45,
      femaleBedsAvailable: 22,
      pediatricBeds: 30,
      pediatricBedsAvailable: 12,
      standardBeds: 120,
      standardBedsAvailable: 60,
      ventilators: 20,
      ventilatorsAvailable: 12,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 890 1234',
      contactEmail: 'jazan.specialized@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 5,
      nicuBedsAvailable: 3,
      hasStrokeUnit: true,
      traumaLevel: TraumaLevel.LEVEL_2,
      hasCardiologyCenter: true,
    },
  ];

  for (const hospital of hospitals) {
    try {
      await prisma.hospital.upsert({
        where: { id: hospital.id },
        update: hospital,
        create: hospital,
      });
      console.log(`✅ Hospital ${hospital.name} seeded/updated`);
    } catch (error) {
      console.error(`❌ Error seeding hospital ${hospital.name}:`, error);
    }
  }

  console.log('✅ Hospitals with UUIDs seeded successfully!');
  console.log('📋 Hospital ID Mapping:');
  for (const [key, id] of Object.entries(HOSPITAL_IDS)) {
    const hospital = hospitals.find(h => h.id === id);
    console.log(`  ${key}: ${id} (${hospital?.name})`);
  }
}

// Run the seeding
seedHospitalsWithUUIDs()
  .then(() => {
    console.log('🎉 Hospital seeding completed!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('💥 Hospital seeding failed:', error);
    process.exit(1);
  });
