import { PrismaClient, HospitalStatus, TraumaLevel } from '@prisma/client';
import { v5 as uuidv5 } from 'uuid';

const prisma = new PrismaClient();
// Deterministic namespace so re-running seed upserts same hospitals instead of creating duplicates
const HOSPITAL_SEED_NAMESPACE = 'a1b2c3d4-e5f6-5789-0abc-def012345678';

export async function seedHospitals() {
  console.log('🏥 Seeding hospitals...');
  
  const hospitals = [
    // Major Hospitals with full services
    {
      id: uuidv5('Jazan General Hospital (JGH)', HOSPITAL_SEED_NAMESPACE),
      name: 'Jazan General Hospital (JGH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.8957234,
      longitude: 42.5557874,
      icuBeds: 20,
      icuBedsAvailable: 10,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 40,
      maleBedsAvailable: 15,
      femaleBeds: 35,
      femaleBedsAvailable: 12,
      pediatricBeds: 15,
      pediatricBedsAvailable: 5,
      standardBeds: 90,
      standardBedsAvailable: 32,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 54 930 0261',
      contactEmail: 'jgh@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('King Fahad Central Hospital (KFCH)', HOSPITAL_SEED_NAMESPACE),
      name: 'King Fahad Central Hospital (KFCH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.9220163,
      longitude: 42.7355263,
      icuBeds: 30,
      icuBedsAvailable: 12,
      picuBeds: 8,
      picuBedsAvailable: 3,
      maleBeds: 60,
      maleBedsAvailable: 20,
      femaleBeds: 55,
      femaleBedsAvailable: 18,
      pediatricBeds: 25,
      pediatricBedsAvailable: 8,
      standardBeds: 140,
      standardBedsAvailable: 46,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 50 503 6789',
      contactEmail: 'kfch@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Prince Mohammed Bin Nasser Hospital (PMNH)', HOSPITAL_SEED_NAMESPACE),
      name: 'Prince Mohammed Bin Nasser Hospital (PMNH)',
      address: 'Jazan, Saudi Arabia',
      latitude: 16.9951348,
      longitude: 42.6183107,
      icuBeds: 15,
      icuBedsAvailable: 7,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 35,
      maleBedsAvailable: 12,
      femaleBeds: 30,
      femaleBedsAvailable: 10,
      pediatricBeds: 15,
      pediatricBedsAvailable: 5,
      standardBeds: 80,
      standardBedsAvailable: 27,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 56 128 4567',
      contactEmail: 'pmnh@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    // Regional Hospitals with varied services
    {
      id: uuidv5('Samtah General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Samtah General Hospital',
      address: 'Samtah, Jazan, Saudi Arabia',
      latitude: 16.606612,
      longitude: 42.941007,
      icuBeds: 10,
      icuBedsAvailable: 4,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 25,
      maleBedsAvailable: 10,
      femaleBeds: 25,
      femaleBedsAvailable: 10,
      pediatricBeds: 10,
      pediatricBedsAvailable: 4,
      standardBeds: 60,
      standardBedsAvailable: 24,
      hasStemiService: false,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 58 211 9876',
      contactEmail: 'samtah@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Abu Arish General Hospital (AAGH)', HOSPITAL_SEED_NAMESPACE),
      name: 'Abu Arish General Hospital (AAGH)',
      address: 'Abu Arish, Jazan, Saudi Arabia',
      latitude: 16.9770664,
      longitude: 42.8732559,
      icuBeds: 12,
      icuBedsAvailable: 5,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 30,
      maleBedsAvailable: 15,
      femaleBeds: 30,
      femaleBedsAvailable: 12,
      pediatricBeds: 12,
      pediatricBedsAvailable: 5,
      standardBeds: 72,
      standardBedsAvailable: 32,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 55 987 6321',
      contactEmail: 'aagh@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    // Smaller hospitals with limited services
    {
      id: uuidv5('Sabya General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Sabya General Hospital',
      latitude: 17.1525193,
      longitude: 42.6473855,
      icuBeds: 10,
      icuBedsAvailable: 5,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 20,
      maleBedsAvailable: 10,
      femaleBeds: 20,
      femaleBedsAvailable: 10,
      pediatricBeds: 10,
      pediatricBedsAvailable: 5,
      standardBeds: 50,
      standardBedsAvailable: 25,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 123 4567',
      contactEmail: 'sabya@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 5,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Baysh General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Baysh General Hospital',
      latitude: 17.4397852,
      longitude: 42.5274381,
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 234 5678',
      contactEmail: 'baysh@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Al-Hurrath General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Al-Hurrath General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      latitude: 17.10979,
      longitude: 42.7693838,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 345 6789',
      contactEmail: 'alhurrath@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Al-Darb General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Al-Darb General Hospital',
      latitude: 17.7077154,
      longitude: 42.2166516,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 456 7890',
      contactEmail: 'aldarb@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Al-Rayth General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Al-Rayth General Hospital',
      latitude: 17.6167942,
      longitude: 42.8273415,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 567 8901',
      contactEmail: 'alrayth@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Al-Tuwal General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Al-Tuwal General Hospital',
      latitude: 16.5345717,
      longitude: 42.9476277,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 678 9012',
      contactEmail: 'altuwal@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Al-Aridha General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Al-Aridha General Hospital',
      latitude: 17.0446963,
      longitude: 43.0445554,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 789 0123',
      contactEmail: 'alaridha@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Al-Muwassam General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Al-Muwassam General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 890 1234',
      contactEmail: 'almuwassam@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Ahad Al-Masarhah General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Ahad Al-Masarhah General Hospital',
      latitude: 16.733231,
      longitude: 42.937143,
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 901 2345',
      contactEmail: 'ahad@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Bani Malik General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Bani Malik General Hospital',
      latitude: 17.3306284,
      longitude: 43.1159548,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 012 3456',
      contactEmail: 'banimalik@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Eradah Mental Health Complex', HOSPITAL_SEED_NAMESPACE),
      name: 'Eradah Mental Health Complex',
      icuBeds: 10,
      icuBedsAvailable: 5,
      picuBeds: 5,
      picuBedsAvailable: 2,
      maleBeds: 20,
      maleBedsAvailable: 10,
      femaleBeds: 20,
      femaleBedsAvailable: 10,
      pediatricBeds: 10,
      pediatricBedsAvailable: 5,
      standardBeds: 50,
      standardBedsAvailable: 25,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 123 4567',
      contactEmail: 'eradah@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 5,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Chest Diseases Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Chest Diseases Hospital',
      icuBeds: 8,
      icuBedsAvailable: 4,
      picuBeds: 4,
      picuBedsAvailable: 2,
      maleBeds: 15,
      maleBedsAvailable: 8,
      femaleBeds: 15,
      femaleBedsAvailable: 8,
      pediatricBeds: 8,
      pediatricBedsAvailable: 4,
      standardBeds: 40,
      standardBedsAvailable: 20,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 234 5678',
      contactEmail: 'chest@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 4,
      nicuBedsAvailable: 2,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Al-Aidabi General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Al-Aidabi General Hospital',
      latitude: 17.2388064,
      longitude: 42.9098925,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 345 6789',
      contactEmail: 'alaidabi@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Dhamad General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Dhamad General Hospital',
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 456 7890',
      contactEmail: 'dhamad@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Farasan General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Farasan General Hospital',
      latitude: 16.6954553,
      longitude: 42.1188235,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 567 8901',
      contactEmail: 'farasan@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Fayfa General Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Fayfa General Hospital',
      latitude: 17.2682963,
      longitude: 43.1134234,
      icuBeds: 6,
      icuBedsAvailable: 3,
      picuBeds: 3,
      picuBedsAvailable: 1,
      maleBeds: 12,
      maleBedsAvailable: 6,
      femaleBeds: 12,
      femaleBedsAvailable: 6,
      pediatricBeds: 6,
      pediatricBedsAvailable: 3,
      standardBeds: 30,
      standardBedsAvailable: 15,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 678 9012',
      contactEmail: 'fayfa@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 3,
      nicuBedsAvailable: 1,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Jazan Specialized Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Jazan Specialized Hospital',
      latitude: 16.806384,
      longitude: 42.6555153,
      icuBeds: 15,
      icuBedsAvailable: 8,
      picuBeds: 8,
      picuBedsAvailable: 4,
      maleBeds: 30,
      maleBedsAvailable: 15,
      femaleBeds: 30,
      femaleBedsAvailable: 15,
      pediatricBeds: 15,
      pediatricBedsAvailable: 8,
      standardBeds: 60,
      standardBedsAvailable: 30,
      hasStemiService: true,
      hasStrokeService: true,
      hasTraumaService: true,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 789 0123',
      contactEmail: 'jazan.specialized@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 8,
      nicuBedsAvailable: 4,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('PHC Centers', HOSPITAL_SEED_NAMESPACE),
      name: 'PHC Centers',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.AVAILABLE,
      contactPhone: '+966 55 890 1234',
      contactEmail: 'phc@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Private Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Private Hospital',
      address: 'Various Private Locations',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 901 2345',
      contactEmail: 'private@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
    {
      id: uuidv5('Other Hospital', HOSPITAL_SEED_NAMESPACE),
      name: 'Other Hospital',
      address: 'External Healthcare Facility',
      icuBeds: 0,
      icuBedsAvailable: 0,
      picuBeds: 0,
      picuBedsAvailable: 0,
      maleBeds: 0,
      maleBedsAvailable: 0,
      femaleBeds: 0,
      femaleBedsAvailable: 0,
      pediatricBeds: 0,
      pediatricBedsAvailable: 0,
      standardBeds: 0,
      standardBedsAvailable: 0,
      hasStemiService: false,
      hasStrokeService: false,
      hasTraumaService: false,
      cluster: 'Jazan',
      status: HospitalStatus.ACTIVE,
      contactPhone: '+966 55 012 3456',
      contactEmail: 'other@moh.gov.sa',
      emergencyDeptStatus: 'available',
      nicuBeds: 0,
      nicuBedsAvailable: 0,
      hasStrokeUnit: false,
      traumaLevel: TraumaLevel.NONE,
      hasCardiologyCenter: false,
    },
  ];

  for (const hospital of hospitals) {
    try {
      await prisma.hospital.upsert({
        where: { id: hospital.id },
        update: hospital,
        create: hospital,
      });
    } catch (error) {
      console.log(`⚠️  Hospital ${hospital.name} already exists, skipping...`);
    }
  }

  console.log(`✅ Hospitals seeded successfully`);
}
